#!/usr/bin/env php
<?php

declare(strict_types=1);

defined('YII_DEBUG') || define('YII_DEBUG', getenv('YII_DEBUG') === '1');
defined('YII_ENV') || define('YII_ENV', getenv('YII_ENV') ?: 'prod');

require __DIR__ . '/bootstrap.php';

$config = require __DIR__ . '/config/console.php';

exit((new yii\console\Application($config))->run());
