#!/usr/bin/env php
<?php

error_reporting(E_ALL & ~E_DEPRECATED & ~E_USER_DEPRECATED);

$config = __DIR__ . '/config/console.php';

require_once __DIR__ . '/../../vendor/yiisoft/yii/framework/yiic.php';
